runs:
  using: "composite"
  steps:
    - run: |
        git clone https://github.com/couchbase/couchbase-cxx-client.git && cd couchbase-cxx-client
        echo -e '\ninstall(DIRECTORY couchbase/ DESTINATION include/couchbase)\ninstall(TARGETS couchbase_cxx_client DESTINATION lib)' | sudo tee -a CMakeLists.txt
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
        make -j ${{env.proc_num}} && sudo make install
      shell: bash