name: Build on Macos

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  proc_num: $(sysctl -n hw.logicalcpu)

jobs:
  compile-with-make-cmake-protobuf21:
    runs-on: macos-latest # https://github.com/actions/runner-images

    steps:
    - uses: actions/checkout@v2
    
    - name: install dependences
      run: |
           brew install protobuf
           brew install openssl gnu-getopt coreutils gflags leveldb pegtl
           brew uninstall cmake
           brew tap couchbaselabs/homebrew-couchbase
           brew install couchbase-cxx-client

    - name: compile with make
      run: |
        GETOPT_PATH=$(brew --prefix gnu-getopt)/bin
        export PATH=$GETOPT_PATH:$PATH
        ./config_brpc.sh --header="$(brew --prefix)/include" --libs="$(brew --prefix)/lib"
        make -j ${{env.proc_num}} && make clean

    - name: compile with cmake
      run: |
        echo "CMAKE_PREFIX_PATH=$(brew --prefix protobuf@21)"
        mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$(brew --prefix protobuf@21) ..
        make -j ${{env.proc_num}} && make clean

  compile-with-make-cmake-protobuf29:
    runs-on: macos-latest # https://github.com/actions/runner-images

    steps:
      - uses: actions/checkout@v2

      - name: install dependences
        run: |
          brew install openssl gnu-getopt coreutils gflags leveldb
          # abseil 20230125.3
          curl -o abseil.rb   https://raw.githubusercontent.com/Homebrew/homebrew-core/b85b8dbf23ad509f163677a88ac72268f31e9c4a/Formula/abseil.rb
          # protobuf 23.3
          curl -o protobuf.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/b85b8dbf23ad509f163677a88ac72268f31e9c4a/Formula/protobuf.rb
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install --formula --ignore-dependencies ./abseil.rb ./protobuf.rb
          brew uninstall cmake
          brew tap couchbaselabs/homebrew-couchbase
          brew install couchbase-cxx-client


      - name: compile with make
        run: |
          GETOPT_PATH=$(brew --prefix gnu-getopt)/bin
          export PATH=$GETOPT_PATH:$PATH
           ./config_brpc.sh --header="$(brew --prefix)/include" --libs="$(brew --prefix)/lib"
          make -j ${{env.proc_num}} && make clean

      - name: compile with cmake
        run: |
          mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$(brew --prefix protobuf@29) ..
          make -j ${{env.proc_num}} && make clean

  compile-with-bazel:
    runs-on: macos-latest # https://github.com/actions/runner-images

    steps:
      - uses: actions/checkout@v2
      - run: bazel build --verbose_failures -- //:brpc -//example/...
